Add database
alexrad555/java-filmorate pull request #5
Opened 2023-11-19 20:15 UTC by alexrad555

2023-11-20 07:55 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2023-11-20 07:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getById(@PathVariable Integer id) {
а зачем поменяли на Integer?

2023-11-20 07:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> -public class Film extends BaseUnit {
зачем убрали?

2023-11-20 07:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final FilmStorage filmStorage;
а какую именно имплементацию инжектите?

2023-11-20 07:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final UserStorage userStorage;
а какую именно имплементацию инжектите?

2023-11-20 07:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                        .genres(new HashSet<>(genreStorage.getFilmGenres(it.getId())))
а если filmStorage.getAll() вернет 1000 фильмов, то есть вы получается сделаете еще 1000 запросов - что плохо. вместо этого в запрос в методе filmStorage.getAll() добавьте join с таблице жанров

2023-11-20 07:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                        .mpa(mpaStorage.getById(it.getMpa().getId()))
тоже самое

2023-11-20 07:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Genre> genres = new HashSet<>(genreStorage.getFilmGenres(film.getId()));
смотрите коммент выше

2023-11-20 07:55 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                        .genres(new HashSet<>(genreStorage.getFilmGenres(it.getId())))
коммент выше

2023-11-20 14:18 UTC, alexrad555 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getById(@PathVariable Integer id) {
Была ошибка при получении данных с базы, и в процессе исправления везде перешел на Integer

2023-11-20 14:36 UTC, alexrad555 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> -public class Film extends BaseUnit {
Отказался от базового класса и изменил анотации

2023-11-20 16:37 UTC, alexrad555 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film getById(@PathVariable Integer id) {
Мне везде придется переделывать на Long, и в HeshSet, это обязательно нужно переделывать? много придется переделывать

2023-11-20 18:30 UTC, alexrad555 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private final FilmStorage filmStorage;
Исправил добавил Qualifier

2023-11-21 04:07 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-11-21 07:08 UTC, merged